### ISSUE TITLE
[Forum] Preserve New Topic Contents Upon Closing Modal

### ISSUE THREAD

**Issue by Mesharsky** [aXenDeveloper/vitnode#202]
Presently, when a modal opens for creating a new topic and a user inadvertently clicks outside the modal, all the entered topic contents are lost.

I propose implementing a mechanism to store the entered contents temporarily, either by utilizing session storage or by providing two methods for creating a topic: via modal and on a separate page. This approach would cater to users who prefer avoiding modal-based interactions, particularly when composing lengthy topics or posts. Additionally, having a separate page would offer more space for content creation.

**Comment by aXenDeveloper** [comment]
Yes, I want to implement [Parallel Routes](https://nextjs.org/docs/app/building-your-application/routing/parallel-routes) for every dialogs. Maybe in **0.2.0** version.

Protection about click outside dialog will be enable in **0.2.0** version => https://github.com/aXenDeveloper/vitnode/issues/135
