### ISSUE TITLE
[Forum] Topics can be created blank

### ISSUE THREAD

**Issue by Mesharsky** [aXenDeveloper/vitnode#214]
There is a bug where you can create blank topics that can't be accessed at all inside forum category by making title just empty "spaces"
Basically space key on keyboard.

Same with topic content

Example: https://frontend.vitnode.com/pl/topic/--11

This thread also cannot be accessed because of missing title: https://frontend.vitnode.com/pl/topic/--10

Make title and content require actuall characters and block "Save" button to prevent that

**Comment by aXenDeveloper** [comment]
Thank you!
The patch has also been applied to the demo site.
